CREATE TABLE "GAB_5339_APRVL"(
 "PURCHASE_ORDER" VARCHAR(7) NOT NULL ,
 "DATE_ORDER" DATE NOT NULL,
 "VENDOR" VARCHAR(6) NOT NULL ,
 "AMOUNT" NUMERIC(15,2),
 "DATE_DUE" DATE NOT NULL ,
 "ORIGINATOR" VARCHAR(8) NOT NULL ,
 "APPROVER" VARCHAR(8),
 "APPROVED_DATE" DATETIME,
 "REVIEWER_1" VARCHAR(8),
 "REVIEWED_1_DATE" DATETIME,
 "REVIEWER_2" VARCHAR(8),
 "REVIEWED_2_DATE" DATETIME,
 PRIMARY KEY(PURCHASE_ORDER,DATE_ORDER));